[window]
opacity = 0.9
decorations = "none"
padding = { x = 8, y = 6 }
dynamic_padding = true
startup_mode = "Windowed"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.selection]
text = "#1e1e2e"
background = "#f5c2e7"

[colors.normal]
black =   "#45475a"
red =     "#f38ba8"
green =   "#a6e3a1"
yellow =  "#f9e2af"
blue =    "#89b4fa"
magenta = "#f5c2e7"
cyan =    "#94e2d5"
white =   "#bac2de"

[colors.bright]
black =   "#585b70"
red =     "#f38ba8"
green =   "#a6e3a1"
yellow =  "#f9e2af"
blue =    "#89b4fa"
magenta = "#f5c2e7"
cyan =    "#94e2d5"
white =   "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#f38ba8"

[env]
TERM = "xterm-256color"

